services:
  - type: web
    name: legacy-west-lead-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: CLOSE_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: NODE_VERSION
        value: 20
